# Generated by Django 2.1.2 on 2018-11-07 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=200)),
                ('refresh_token', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=50)),
                ('expiration_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SyllaShareToken',
            fields=[
                ('syllashare_token', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user_data.User')),
                ('expiration_date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='servicetokens',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_data.User'),
        ),
        migrations.AlterUniqueTogether(
            name='servicetokens',
            unique_together={('user', 'provider')},
        ),
    ]
