# Generated by Django 2.1.2 on 2018-10-22 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_initial'),
        ('syllatokens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=200)),
                ('refresh_token', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=50)),
                ('expiration_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_data.User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='servicetokens',
            unique_together={('user', 'provider')},
        ),
    ]
