# Generated by Django 2.1.1 on 2018-10-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=128, null=True)),
                ('last_name', models.CharField(max_length=128, null=True)),
                ('username', models.CharField(max_length=128)),
                ('profilePicUrl', models.CharField(max_length=128)),
            ],
        ),
    ]
