# Generated by Django 2.1.1 on 2018-10-30 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.CharField(max_length=256)),
                ('year', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=16)),
                ('pic_key', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SyllabusEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_name', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_data.Class')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_data.EventType')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_data.School')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('rating', models.FloatField(null=True)),
                ('website', models.URLField(null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_data.Department')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_data.School')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=128, null=True)),
                ('last_name', models.CharField(max_length=128, null=True)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('email', models.CharField(max_length=128, null=True)),
                ('pic_key', models.CharField(max_length=200, null=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_data.School')),
                ('syllabi', models.ManyToManyField(to='user_data.SyllabusEvent')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_data.Department'),
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_data.School'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_data.Teacher'),
        ),
        migrations.AddField(
            model_name='class',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_data.Term'),
        ),
    ]
