# Generated by Django 2.1.2 on 2018-10-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='picKey',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='pic_key',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
