# Generated by Django 2.1.2 on 2018-10-25 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0002_auto_20181025_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='picKey',
            new_name='pic_key',
        ),
    ]
