# Generated by Django 2.1.1 on 2018-11-01 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0003_remove_syllabusevent_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.RenameField(
            model_name='syllabusevent',
            old_name='entry_name',
            new_name='event_name',
        ),
        migrations.RemoveField(
            model_name='syllabusevent',
            name='class_from',
        ),
        migrations.AddField(
            model_name='class',
            name='class_description',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='syllabusevent',
            name='from_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_data.Class'),
        ),
        migrations.AddField(
            model_name='syllabusevent',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_data.User'),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_number',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_data.Teacher'),
        ),
        migrations.AlterField(
            model_name='syllabusevent',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='syllabusevent',
            name='from_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_data.Group'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(to='user_data.Group'),
        ),
    ]
